<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Actividades;

class ActividadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $actividades = [
            ['codi_actividad'=>'11103','desc_actividad'=>'ENVASADOS Y CONSERVACION DE FRUTAS Y LEGUMBRES'],
            ['codi_actividad'=>'34701','desc_actividad'=>'OPTICAS'],
            ['codi_actividad'=>'11101','desc_actividad'=>'MATANZA DE GANADO Y PREPARACION Y CONSERVACION DE CARNE'],
            ['codi_actividad'=>'11102','desc_actividad'=>'FABRICACION DE PRODUCTOS LACTEOS'],
            ['codi_actividad'=>'11104','desc_actividad'=>'ELABORACION DE PESCADO'],
            ['codi_actividad'=>'11105','desc_actividad'=>'FABRICACION DE ACEITE Y GRASAS VEGETALES Y ANIMALES'],
            ['codi_actividad'=>'11106','desc_actividad'=>'PRODUCTOS DE MOLINERIA'],
            ['codi_actividad'=>'11107','desc_actividad'=>'FABRICACION DE PRODUCTOS DE PANADERIA'],
            ['codi_actividad'=>'11108','desc_actividad'=>'FABRICAS Y REFINERIAS DE AZUCAR'],
            ['codi_actividad'=>'11109','desc_actividad'=>'FABRICACION DE CACAO'],
            ['codi_actividad'=>'11110','desc_actividad'=>'ELABORACION DE PRODUCTOS ALIMENTICIOS DIVERSOS'],
            ['codi_actividad'=>'11111','desc_actividad'=>'ELABORACION DE ALIMENTOS PREPARADOS PARA ANIMALES'],
            ['codi_actividad'=>'11201','desc_actividad'=>'DESTILACION'],
            ['codi_actividad'=>'11202','desc_actividad'=>'INDUSTRIAS VINICOLAS'],
            ['codi_actividad'=>'11203','desc_actividad'=>'BEBIDAS MALTEADAS Y MALTAS'],
            ['codi_actividad'=>'11204','desc_actividad'=>'INDUSTRIAS DE BEBIDAS NO ALCOHOLICAS Y AGUAS GASEOSAS'],
            ['codi_actividad'=>'11301','desc_actividad'=>'INDUSTRIA DEL TABACO'],
            ['codi_actividad'=>'12101','desc_actividad'=>'HILADO'],
            ['codi_actividad'=>'12102','desc_actividad'=>'ARTICULOS CONFECCIONADOS DE MATERIALES TEXTILES'],
            ['codi_actividad'=>'43305','desc_actividad'=>'CARPINTERIA DE MADERA'],
            ['codi_actividad'=>'12103','desc_actividad'=>'FABRICA DE TEJIDOS DE PUNTO'],
            ['codi_actividad'=>'12104','desc_actividad'=>'FABRICACION DE TAPICES Y ALFOMBRAS'],
            ['codi_actividad'=>'12105','desc_actividad'=>'CORDELERIA'],
            ['codi_actividad'=>'12106','desc_actividad'=>'FABRICACION DE TEXTILES N.E.P.'],
            ['codi_actividad'=>'12201','desc_actividad'=>'FABRICACION DE PRENDAS DE VESTIR EXCEPTO CALZADO'],
            ['codi_actividad'=>'12301','desc_actividad'=>'CURTIDURIAS Y TALLERES DE ACABADO'],
            ['codi_actividad'=>'12302','desc_actividad'=>'INDUSTRIA DE LA PREPARACION Y TEÑIDO DE PIELES'],
            ['codi_actividad'=>'12303','desc_actividad'=>'FABRICACION DE ARTICULOS DE CUERO Y SUCEDONEOS DE CUERO'],
            ['codi_actividad'=>'12401','desc_actividad'=>'FABRICACION DE CALZADO EXCEPTO EL DE CAUCHO VULCANIZADO O  MOLDEADO DE PLASTICO'],
            ['codi_actividad'=>'13101','desc_actividad'=>'ASERRADEROS'],
            ['codi_actividad'=>'13102','desc_actividad'=>'FABRICACION DE ENVASES DE MADERA Y DE CAÑA Y ARTICULOS MENUDOS DE CAÑA'],
            ['codi_actividad'=>'13103','desc_actividad'=>'FABRICACION DE PRODUCTOS DE MADERA Y CORCHO'],
            ['codi_actividad'=>'13201','desc_actividad'=>'FABRICACION DE MUEBLES Y ACCESORIOS'],
            ['codi_actividad'=>'14101','desc_actividad'=>'FABRICACION DE PULPA DE MADERA'],
            ['codi_actividad'=>'14102','desc_actividad'=>'FABRICACION DE ENVASES Y CAJAS DE PAPEL Y DE CARTÓN'],
            ['codi_actividad'=>'14103','desc_actividad'=>'FABRICACION DE ARTÍCULOS DE PULPA'],
            ['codi_actividad'=>'14201','desc_actividad'=>'IMPRENTAS'],
            ['codi_actividad'=>'15101','desc_actividad'=>'FABRICACION DE SUSTANCIAS QUÍMICAS INDUSTRIALES BASICAS EXCEPTO ABONOS'],
            ['codi_actividad'=>'15102','desc_actividad'=>'FABRICACION DE ABONOS Y PLAGUICIDAS'],
            ['codi_actividad'=>'15103','desc_actividad'=>'FABRICACION DE RESINAS SINTÉTICAS'],
            ['codi_actividad'=>'15201','desc_actividad'=>'FABRICACION DE PINTURAS'],
            ['codi_actividad'=>'15202','desc_actividad'=>'FABRICACION DE PRODUCTOS FARMACÉUTICOS Y MEDICAMENTOS'],
            ['codi_actividad'=>'15203','desc_actividad'=>'FABRICACION DE JABONES Y PREPARADOS DE LIMPIEZA'],
            ['codi_actividad'=>'15204','desc_actividad'=>'FABRICACION DE PRODUCTOS QUÍMICOS'],
            ['codi_actividad'=>'15301','desc_actividad'=>'REFINERIAS DE PETROLEO'],
            ['codi_actividad'=>'15302','desc_actividad'=>'FABRICACION DE PRODUCTOS DIVERSOS DERIVADOSDEL PETRÓLEO Y DEL CARBÓN'],
            ['codi_actividad'=>'15401','desc_actividad'=>'INDUSTRIAS DE LLANTAS Y CÁMARAS'],
            ['codi_actividad'=>'15402','desc_actividad'=>'FABRICACION DE PRODUCTOS DE CAUCHO'],
            ['codi_actividad'=>'15403','desc_actividad'=>'FABRICACION DE PRODUCTOS PLÁSTICOS'],
            ['codi_actividad'=>'16101','desc_actividad'=>'FABRICACION DE OBJETOS DE BARRO'],
            ['codi_actividad'=>'16201','desc_actividad'=>'FABRICACION DE VIDRIO Y PRODUCTOS DE VIDRIO'],
            ['codi_actividad'=>'16301','desc_actividad'=>'FABRICACION DE OTROS PRODUCTOS DE ARCILLA PARA CONSTRUCCIÓN'],
            ['codi_actividad'=>'16302','desc_actividad'=>'FABRICACION DE CEMENTO'],
            ['codi_actividad'=>'17101','desc_actividad'=>'INDUSTRIAS BÁSICAS DE HIERRO Y ACERO'],
            ['codi_actividad'=>'17201','desc_actividad'=>'INDUSTRIAS BÁSICAS DE METALES NO FERROSOS'],
            ['codi_actividad'=>'18101','desc_actividad'=>'FABRICACION DE CUCHILLERÍA'],
            ['codi_actividad'=>'18102','desc_actividad'=>'FABRICACION DE MUEBLES Y ACCESORIOS PRINCIPALES METÁLICOS'],
            ['codi_actividad'=>'18103','desc_actividad'=>'FABRICACION DE PRODUCTOS METÁLICOS ESTRUCTURALES'],
            ['codi_actividad'=>'18104','desc_actividad'=>'FABRICACION DE PRODUCTOS METÁLICOS'],
            ['codi_actividad'=>'18201','desc_actividad'=>'CONSTRUCCIÓN DE MOTORES Y TURBINAS'],
            ['codi_actividad'=>'18202','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINARIAS Y EQUIPO PARA LA AGRICULTURA'],
            ['codi_actividad'=>'18203','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINARIAS PARA TRABAJAR LOS METALES Y LA MADERA'],
            ['codi_actividad'=>'18204','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINARIA Y EQUIPOS ESPECIALES PARA LAS INDUSTRIAS'],
            ['codi_actividad'=>'18205','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINARIAS DE OFICINA'],
            ['codi_actividad'=>'18206','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINARIA Y EQUIPO N.E.P.'],
            ['codi_actividad'=>'18301','desc_actividad'=>'CONSTRUCCIÓN DE MAQUINAS Y APARATOS INDUSTRIALES ELECTRICOS'],
            ['codi_actividad'=>'18302','desc_actividad'=>'CONSTRUCCIÓN DE EQUIPOS Y APARATOS DE RADIO'],
            ['codi_actividad'=>'18303','desc_actividad'=>'CONSTRUCCIÓN DE APARATOS Y ACCESORIOS ELECTRICOS DE USO DOMÉSTICO'],
            ['codi_actividad'=>'18304','desc_actividad'=>'CONSTRUCCIÓN DE APARATOS Y SUMINISTROS ELECTRICOS'],
            ['codi_actividad'=>'18401','desc_actividad'=>'CONSTRUCCIONES NAVALES Y REPARACIÓN DE BARCOS'],
            ['codi_actividad'=>'18402','desc_actividad'=>'CONSTRUCCIÓN DE EQUIPO FERROVIARIO'],
            ['codi_actividad'=>'18403','desc_actividad'=>'FABRICACION DE VEHÍCULOS AUTOMÓVILES'],
            ['codi_actividad'=>'18404','desc_actividad'=>'FABRICACION DE MOTOCICLETAS Y BICICLETAS'],
            ['codi_actividad'=>'18405','desc_actividad'=>'FABRICACION DE AERONAVES'],
            ['codi_actividad'=>'18406','desc_actividad'=>'CONSTRUCCIÓN DE MATERIAL DE TRANSPORTE N.E.P.'],
            ['codi_actividad'=>'18501','desc_actividad'=>'FABRICACION DE EQUIPO PROFESIONAL Y CIENTÍFICO'],
            ['codi_actividad'=>'18502','desc_actividad'=>'FABRICACION DE APARATOS FOTOGRÁFICOS É INSTRUMENTOS DE OPTICA'],
            ['codi_actividad'=>'18503','desc_actividad'=>'FABRICACION DE RELOJES'],
            ['codi_actividad'=>'19101','desc_actividad'=>'FABRICACION DE JOYAS Y ARTÍCULOS CONEXOS'],
            ['codi_actividad'=>'19201','desc_actividad'=>'FABRICACION DE INSTRUMENTOS DE MUSICA'],
            ['codi_actividad'=>'19301','desc_actividad'=>'FABRICACION DE ARTÍCULOS DE DEPORTE Y ATLETÍSMO'],
            ['codi_actividad'=>'19401','desc_actividad'=>'INDUSTRIAS MANUFACTURERAS N.E.P.'],
            ['codi_actividad'=>'20101','desc_actividad'=>'LUZ Y FUERZA ELÉCTRICA'],
            ['codi_actividad'=>'20102','desc_actividad'=>'PRODUCCIÓN Y DISTRIBUCIÓN DE GAS'],
            ['codi_actividad'=>'20103','desc_actividad'=>'SUMINISTRO DE VAPOR Y AGUA CALIENTE'],
            ['codi_actividad'=>'20201','desc_actividad'=>'OBRAS HIDRÁULICAS Y SUMINISTRO DE AGUA'],
            ['codi_actividad'=>'21101','desc_actividad'=>'CONSTRUCCION'],
            ['codi_actividad'=>'31101','desc_actividad'=>'CAFÉ EN GRANO'],
            ['codi_actividad'=>'31102','desc_actividad'=>'CEREALES'],
            ['codi_actividad'=>'31103','desc_actividad'=>'ESPECIERÍAS'],
            ['codi_actividad'=>'31104','desc_actividad'=>'FRUTERIAS'],
            ['codi_actividad'=>'31105','desc_actividad'=>'VERDULERÍA'],
            ['codi_actividad'=>'31106','desc_actividad'=>'MENESTRAS'],
            ['codi_actividad'=>'31107','desc_actividad'=>'TUBERCULOS'],
            ['codi_actividad'=>'31108','desc_actividad'=>'ACEITUNAS'],
            ['codi_actividad'=>'31109','desc_actividad'=>'CACAO'],
            ['codi_actividad'=>'31199','desc_actividad'=>'OTROS PRODUCTOS AGRÍCOLAS COMESTIBLES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'31201','desc_actividad'=>'ALGODÓN'],
            ['codi_actividad'=>'31202','desc_actividad'=>'FLORERIA'],
            ['codi_actividad'=>'31203','desc_actividad'=>'FORRAJES'],
            ['codi_actividad'=>'31204','desc_actividad'=>'SEMILLAS Y PLANTAS'],
            ['codi_actividad'=>'31205','desc_actividad'=>'TABACO EN RAMA'],
            ['codi_actividad'=>'31206','desc_actividad'=>'COCA'],
            ['codi_actividad'=>'31207','desc_actividad'=>'YERBA SECA PARA DIFERENTES USOS'],
            ['codi_actividad'=>'31209','desc_actividad'=>'OTROS PRODUCTOS AGRÍCOLAS NO UTILIZADOS PARA EL CONSUMO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'31301','desc_actividad'=>'PRODUCTOS DE LA CASA'],
            ['codi_actividad'=>'31302','desc_actividad'=>'PESES ORNAMENTALES'],
            ['codi_actividad'=>'31303','desc_actividad'=>'ANIMALES DE CARGA'],
            ['codi_actividad'=>'31304','desc_actividad'=>'COCHINILLA'],
            ['codi_actividad'=>'31305','desc_actividad'=>'ANIMALES DOMESTICOS'],
            ['codi_actividad'=>'31399','desc_actividad'=>'OTROS ANIMALES NO UTILIZADOS EN LA ALIMENTACIÓN Y NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'31401','desc_actividad'=>'AVICOLAS'],
            ['codi_actividad'=>'31402','desc_actividad'=>'CARNICERIA'],
            ['codi_actividad'=>'31403','desc_actividad'=>'GANADO EN PIE'],
            ['codi_actividad'=>'31404','desc_actividad'=>'PESCADERIAS Y AFINES'],
            ['codi_actividad'=>'31405','desc_actividad'=>'ANIMALES PEQUEÑOS'],
            ['codi_actividad'=>'31499','desc_actividad'=>'OTROS ANIMALES VIVOS Y PRODUCTOS PECUARIOS UTILIZADOS EN LA ALIMENTACIÓN Y NO CLASIFICADOS EN LA OTRA PARTE'],
            ['codi_actividad'=>'32101','desc_actividad'=>'PLANTAS MEDICINALES'],
            ['codi_actividad'=>'32102','desc_actividad'=>'TRONCOS PARA ASERRADEROS'],
            ['codi_actividad'=>'32103','desc_actividad'=>'COMERCIO DE MINERALES Y METALES'],
            ['codi_actividad'=>'32199','desc_actividad'=>'OTROS PRODUCTOS EN ESTADO NATURAL NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'32201','desc_actividad'=>'CAUCHO'],
            ['codi_actividad'=>'32202','desc_actividad'=>'PRODUCTOS PROVENIENTES DEL CULTIVO Y/O EXPLOTACIÓN DE OTRAS ESPECIES VEGETALES: GERMEN DE TRIGO'],
            ['codi_actividad'=>'32299','desc_actividad'=>'OTROS PRODUCTOS DERIVADOS NO INDUSTRIALIZADOS'],
            ['codi_actividad'=>'33101','desc_actividad'=>'CAFÉ DE TOSTADURIA'],
            ['codi_actividad'=>'33102','desc_actividad'=>'CONFITERIA'],
            ['codi_actividad'=>'33103','desc_actividad'=>'EMBUTIDOS'],
            ['codi_actividad'=>'33104','desc_actividad'=>'HELADERIAS'],
            ['codi_actividad'=>'33105','desc_actividad'=>'LECHERIA Y CREMERIA'],
            ['codi_actividad'=>'33106','desc_actividad'=>'PANADERIA Y PASTELERIA'],
            ['codi_actividad'=>'33107','desc_actividad'=>'TIENDA DE ABARROTES'],
            ['codi_actividad'=>'33109','desc_actividad'=>'OTROS PRODUCTOS ALIMENTICIOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'33110','desc_actividad'=>'MINIMARKET'],
            ['codi_actividad'=>'33201','desc_actividad'=>'NUTRIMENTOS'],
            ['codi_actividad'=>'33299','desc_actividad'=>'OTROS PRODUCTOS ALIMENTICIOS PREPARADOS PARA ANIMALES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'33301','desc_actividad'=>'LICORERIAS'],
            ['codi_actividad'=>'33302','desc_actividad'=>'CIGARRERIA'],
            ['codi_actividad'=>'33303','desc_actividad'=>'BEBIDAS REFRESCANTES'],
            ['codi_actividad'=>'33399','desc_actividad'=>'OTROS ARTÍCULOS CONEXOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'33401','desc_actividad'=>'ARTICULOS DE TOCADOR E HIGIENE PERSONAL'],
            ['codi_actividad'=>'33402','desc_actividad'=>'FARMACIA'],
            ['codi_actividad'=>'33403','desc_actividad'=>'PRODUCTOS VETERINARIOS'],
            ['codi_actividad'=>'33499','desc_actividad'=>'OTROS PRODUCTOS FARMACÉUTICOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'33501','desc_actividad'=>'GAS PROPANO'],
            ['codi_actividad'=>'33502','desc_actividad'=>'GRIFO'],
            ['codi_actividad'=>'33503','desc_actividad'=>'CARBONERIA'],
            ['codi_actividad'=>'33504','desc_actividad'=>'LUBRICANTES'],
            ['codi_actividad'=>'33505','desc_actividad'=>'RON DE QUEMAR'],
            ['codi_actividad'=>'33599','desc_actividad'=>'OTROS COMBUSTIBLES'],
            ['codi_actividad'=>'34101','desc_actividad'=>'MERCERIA'],
            ['codi_actividad'=>'34102','desc_actividad'=>'ZAPATERIAS'],
            ['codi_actividad'=>'34103','desc_actividad'=>'PELETERIAS'],
            ['codi_actividad'=>'34104','desc_actividad'=>'BAZAR'],
            ['codi_actividad'=>'34105','desc_actividad'=>'SOMBRERERIA (SOMBREROS)'],
            ['codi_actividad'=>'34106','desc_actividad'=>'TELAS Y TEJIDOS'],
            ['codi_actividad'=>'34107','desc_actividad'=>'TRAJES DE BODA Y COMPROMISOS EN GENERAL Y ACCESORIOS'],
            ['codi_actividad'=>'34108','desc_actividad'=>'ARTICULOS PARA EL ARREGLO PERSONAL'],
            ['codi_actividad'=>'34199','desc_actividad'=>'OTRAS TELAS Y TEJIDOS'],
            ['codi_actividad'=>'34201','desc_actividad'=>'APARATOS DOMESTICOS'],
            ['codi_actividad'=>'34202','desc_actividad'=>'ALFOMBRAS'],
            ['codi_actividad'=>'34203','desc_actividad'=>'COLCHONERÍA'],
            ['codi_actividad'=>'34204','desc_actividad'=>'MUEBLERIA (MUEBLES PARA EL HOGAR)'],
            ['codi_actividad'=>'34205','desc_actividad'=>'LENCERIA'],
            ['codi_actividad'=>'34206','desc_actividad'=>'LOCERIA Y CRISTALERIA'],
            ['codi_actividad'=>'34207','desc_actividad'=>'UTENSILIOS DE COCINA'],
            ['codi_actividad'=>'34208','desc_actividad'=>'ARTÍCULOS PARA EL ARREGLO DEL HOGAR Y COMPLEMENTARIOS'],
            ['codi_actividad'=>'34299','desc_actividad'=>'OTROS ARTÍCULOS PARA EL HOGAR NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'34301','desc_actividad'=>'LIBRERÍA Y/O ARTICULOS DE OFICINA'],
            ['codi_actividad'=>'34302','desc_actividad'=>'REVISTAS Y PERIODICOS'],
            ['codi_actividad'=>'34303','desc_actividad'=>'TARJETAS'],
            ['codi_actividad'=>'34399','desc_actividad'=>'OTROS LIBROS'],
            ['codi_actividad'=>'34401','desc_actividad'=>'ARTICULOS ARTESANALES'],
            ['codi_actividad'=>'34402','desc_actividad'=>'ANTIGUEDADES'],
            ['codi_actividad'=>'34403','desc_actividad'=>'PLATERIA'],
            ['codi_actividad'=>'34404','desc_actividad'=>'CASA DE REGALOS'],
            ['codi_actividad'=>'34405','desc_actividad'=>'ARTICULOS RELIGIOSOS'],
            ['codi_actividad'=>'34406','desc_actividad'=>'DISFRACES Y ARTICULOS PARA FIESTAS'],
            ['codi_actividad'=>'34407','desc_actividad'=>'JOYERIA Y RELOJERIA'],
            ['codi_actividad'=>'34408','desc_actividad'=>'CUADROS Y ESCULTURAS'],
            ['codi_actividad'=>'34409','desc_actividad'=>'BRONCERIA'],
            ['codi_actividad'=>'34410','desc_actividad'=>'ARTICULOS DE FILATELIA'],
            ['codi_actividad'=>'34411','desc_actividad'=>'LAMPARAS'],
            ['codi_actividad'=>'34412','desc_actividad'=>'ARTICULOS DE FANTASIA'],
            ['codi_actividad'=>'34413','desc_actividad'=>'ARTICULOS DE PIROTECNIA'],
            ['codi_actividad'=>'34499','desc_actividad'=>'OTROS ARTÍCULOS Y DE LUJO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'34501','desc_actividad'=>'AUTOMOVILES'],
            ['codi_actividad'=>'34502','desc_actividad'=>'BICICLETAS Y SIMILARES'],
            ['codi_actividad'=>'34503','desc_actividad'=>'MOTOCICLETAS Y MOTONETAS'],
            ['codi_actividad'=>'34599','desc_actividad'=>'OTROS AUTOMÓVILES Y OTROS MEDIOS DE TRANSPORTE Y TRACCIÓN PERSONAL NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'34601','desc_actividad'=>'INMUEBLES'],
            ['codi_actividad'=>'34699','desc_actividad'=>'OTROS BIENES RAICES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'34702','desc_actividad'=>'ARMERIA'],
            ['codi_actividad'=>'34703','desc_actividad'=>'ARTICULOS DEPORTIVOS'],
            ['codi_actividad'=>'34704','desc_actividad'=>'CASA DE DISCOS'],
            ['codi_actividad'=>'34705','desc_actividad'=>'EQUIPOS FOTOGRAFICOS Y DE PROYECCION'],
            ['codi_actividad'=>'34706','desc_actividad'=>'INSTRUMENTOS MUSICALES'],
            ['codi_actividad'=>'34707','desc_actividad'=>'JUGUETERIA'],
            ['codi_actividad'=>'34708','desc_actividad'=>'MALETERIA'],
            ['codi_actividad'=>'34709','desc_actividad'=>'CASA DE REMATES'],
            ['codi_actividad'=>'34710','desc_actividad'=>'OBJETOS DE CUERO PARA ANIMALES DE TRACCIÓN'],
            ['codi_actividad'=>'34711','desc_actividad'=>'OBJETOS DE CUERO PARA TRANSPORTE DE ARTÍCULOS PERSONALES'],
            ['codi_actividad'=>'34712','desc_actividad'=>'ARTÍCULOS DOMÉSTICOS DE PLÁSTICO Y ACRÍLICO'],
            ['codi_actividad'=>'34713','desc_actividad'=>'HOJALATERIA'],
            ['codi_actividad'=>'34799','desc_actividad'=>'OTROS ARTÍCULOS DIVERSOS DE USO DURADERO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'35101','desc_actividad'=>'FERTILIZANTES Y PESTICIDAS'],
            ['codi_actividad'=>'35199','desc_actividad'=>'OTROS FERTILIZANTES'],
            ['codi_actividad'=>'35201','desc_actividad'=>'CUERO'],
            ['codi_actividad'=>'35202','desc_actividad'=>'CHATARRA'],
            ['codi_actividad'=>'35203','desc_actividad'=>'PRODUCTOS QUIMICOS INDUSTRIALES ESENCIALES'],
            ['codi_actividad'=>'35204','desc_actividad'=>'PAPEL Y CARBON'],
            ['codi_actividad'=>'35205','desc_actividad'=>'ALCOHOL HIDRATADO'],
            ['codi_actividad'=>'35206','desc_actividad'=>'LEVADURAS Y ESENCIAS'],
            ['codi_actividad'=>'35207','desc_actividad'=>'LANA'],
            ['codi_actividad'=>'35208','desc_actividad'=>'INSUMOS PARA LA INDUSTRIA DEL CALZADO'],
            ['codi_actividad'=>'35209','desc_actividad'=>'MARROQUINES'],
            ['codi_actividad'=>'35299','desc_actividad'=>'OTROS INSUMOS MANUFACTURADOS PARA LA INDUSTRIA DE TRANSFORMACIÓN NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'35301','desc_actividad'=>'FERRETERIA'],
            ['codi_actividad'=>'35302','desc_actividad'=>'CEMENTO'],
            ['codi_actividad'=>'35303','desc_actividad'=>'FIERRO Y ACERO EN VARILLAS'],
            ['codi_actividad'=>'35304','desc_actividad'=>'LADRILLOS'],
            ['codi_actividad'=>'35305','desc_actividad'=>'MADERAS'],
            ['codi_actividad'=>'35306','desc_actividad'=>'MARMOLERIA'],
            ['codi_actividad'=>'35307','desc_actividad'=>'PINTURAS'],
            ['codi_actividad'=>'35308','desc_actividad'=>'SANITARIOS'],
            ['codi_actividad'=>'35309','desc_actividad'=>'VIDRIERIA'],
            ['codi_actividad'=>'35310','desc_actividad'=>'PRODUCTOS DE CANTERAS'],
            ['codi_actividad'=>'35311','desc_actividad'=>'INSUMOS PARA CARPINTERÍA METÁLICA'],
            ['codi_actividad'=>'35399','desc_actividad'=>'OTROS INSUMOS MANUFACTURADOS USADOS PREFERENTEMENTE PARA LA CONSTRUCCIÓN NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'35401','desc_actividad'=>'REPUESTOS DE APARATOS DOMESTICOS'],
            ['codi_actividad'=>'35402','desc_actividad'=>'REPUESTOS DE VEHICULOS AUTOMOTORES'],
            ['codi_actividad'=>'35403','desc_actividad'=>'REPUESTOS DE MOTOS Y BICICLETAS'],
            ['codi_actividad'=>'35404','desc_actividad'=>'REPUESTOS DE MAQUINARIA EN GENERAL'],
            ['codi_actividad'=>'35405','desc_actividad'=>'OTROS REPUESTOS Y ACCESORIOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'36101','desc_actividad'=>'EQUIPOS DE SEGURIDAD E HIGIENE'],
            ['codi_actividad'=>'36102','desc_actividad'=>'EQUIPOS PARA OFICINA'],
            ['codi_actividad'=>'36103','desc_actividad'=>'MUEBLES PARA OFICINA'],
            ['codi_actividad'=>'36104','desc_actividad'=>'MAQUINARIAS'],
            ['codi_actividad'=>'36105','desc_actividad'=>'MAQUINARIAS'],
            ['codi_actividad'=>'36106','desc_actividad'=>'MAQUINARIAS'],
            ['codi_actividad'=>'36107','desc_actividad'=>'MAQUINARIAS'],
            ['codi_actividad'=>'36199','desc_actividad'=>'OTRAS MAQUINARIAS'],
            ['codi_actividad'=>'36201','desc_actividad'=>'PARA COMERCIO'],
            ['codi_actividad'=>'36202','desc_actividad'=>'PARA INGENIERIA'],
            ['codi_actividad'=>'36203','desc_actividad'=>'PARA MEDICINA'],
            ['codi_actividad'=>'36204','desc_actividad'=>'PARA SERVICIOS'],
            ['codi_actividad'=>'36205','desc_actividad'=>'OTROS APARATOS DE MEDICIÓN'],
            ['codi_actividad'=>'36301','desc_actividad'=>'CAMIONES'],
            ['codi_actividad'=>'36302','desc_actividad'=>'CARGADORES'],
            ['codi_actividad'=>'36303','desc_actividad'=>'VEHICULOS DE TRANSPORTE ACUATICO'],
            ['codi_actividad'=>'36399','desc_actividad'=>'OTROS VEHÍCULOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'37101','desc_actividad'=>'TIENDAS DE DEPARTAMENTOS'],
            ['codi_actividad'=>'37102','desc_actividad'=>'CAJAS'],
            ['codi_actividad'=>'37103','desc_actividad'=>'BOLSAS'],
            ['codi_actividad'=>'37104','desc_actividad'=>'BOTELLAS'],
            ['codi_actividad'=>'37105','desc_actividad'=>'HIELO'],
            ['codi_actividad'=>'37106','desc_actividad'=>'CHATARRA'],
            ['codi_actividad'=>'37199','desc_actividad'=>'OTROS BIENES NO IDENTIFICADOS EN LOS GRUPOS ANTERIORES'],
            ['codi_actividad'=>'41101','desc_actividad'=>'BAR'],
            ['codi_actividad'=>'41102','desc_actividad'=>'CAFÉ'],
            ['codi_actividad'=>'41103','desc_actividad'=>'CEVICHERÍA'],
            ['codi_actividad'=>'41104','desc_actividad'=>'CHIFA'],
            ['codi_actividad'=>'41105','desc_actividad'=>'DULCERIA'],
            ['codi_actividad'=>'41106','desc_actividad'=>'HELADERIA'],
            ['codi_actividad'=>'41107','desc_actividad'=>'JUGUERIA'],
            ['codi_actividad'=>'41108','desc_actividad'=>'PARRILLADA'],
            ['codi_actividad'=>'41109','desc_actividad'=>'PICANTERIA'],
            ['codi_actividad'=>'41110','desc_actividad'=>'POLLERIA'],
            ['codi_actividad'=>'41111','desc_actividad'=>'RECREO'],
            ['codi_actividad'=>'41112','desc_actividad'=>'RESTAURANTE'],
            ['codi_actividad'=>'41113','desc_actividad'=>'PIZZERIA'],
            ['codi_actividad'=>'41114','desc_actividad'=>'FUENTE DE SODA'],
            ['codi_actividad'=>'41115','desc_actividad'=>'SANDWICHERÍA'],
            ['codi_actividad'=>'41116','desc_actividad'=>'SNACK BAR'],
            ['codi_actividad'=>'41117','desc_actividad'=>'COMIDA AL PASO'],
            ['codi_actividad'=>'41199','desc_actividad'=>'OTROS SERVICIOS DE ALIMENTACIÓN Y BEBIDAS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'41201','desc_actividad'=>'ALQUILER DE TRAJES'],
            ['codi_actividad'=>'41202','desc_actividad'=>'LAVANDERIA Y TINTORERIA'],
            ['codi_actividad'=>'41203','desc_actividad'=>'LUSTRADO DE CALZADO'],
            ['codi_actividad'=>'41204','desc_actividad'=>'REPARACION DE CALZADO'],
            ['codi_actividad'=>'41205','desc_actividad'=>'TALLER DE SOMBRERIA'],
            ['codi_actividad'=>'41206','desc_actividad'=>'SASTRERÍA'],
            ['codi_actividad'=>'41207','desc_actividad'=>'TALLER DE MODAS'],
            ['codi_actividad'=>'41208','desc_actividad'=>'BORDADURIA'],
            ['codi_actividad'=>'41209','desc_actividad'=>'REMALLADORA DE MEDIAS'],
            ['codi_actividad'=>'41210','desc_actividad'=>'TALLER DE ESTAMPADOS Y PINTURAS DE TELAS'],
            ['codi_actividad'=>'41299','desc_actividad'=>'OTROS SERVICIOS DE VESTIMENTA NO CLASIFICADAS EN OTRA PARTE'],
            ['codi_actividad'=>'41301','desc_actividad'=>'ALQUILER DE INMUEBLES'],
            ['codi_actividad'=>'41302','desc_actividad'=>'CENTROS VACACIONALES'],
            ['codi_actividad'=>'41303','desc_actividad'=>'HOSTAL'],
            ['codi_actividad'=>'41304','desc_actividad'=>'HOSTAL RESIDENCIAL'],
            ['codi_actividad'=>'41305','desc_actividad'=>'HOTEL'],
            ['codi_actividad'=>'41306','desc_actividad'=>'HOTEL RESIDENCIAL'],
            ['codi_actividad'=>'41307','desc_actividad'=>'MOTELES'],
            ['codi_actividad'=>'41308','desc_actividad'=>'PENSION'],
            ['codi_actividad'=>'41309','desc_actividad'=>'MANTENIMIENTO Y LIMPIEZA DE INMUEBLES'],
            ['codi_actividad'=>'41310','desc_actividad'=>'OTROS SERVICIOS DE VIVIENDA Y ALOJAMIENTO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'41401','desc_actividad'=>'BAÑOS PUBLICOS'],
            ['codi_actividad'=>'41402','desc_actividad'=>'PEDICURIA Y/O MANICURIA'],
            ['codi_actividad'=>'41403','desc_actividad'=>'PELUQUERIA'],
            ['codi_actividad'=>'41404','desc_actividad'=>'SALONES DE BELLEZA Y PEINADOS'],
            ['codi_actividad'=>'41405','desc_actividad'=>'BAÑOS SAUNA O BAÑOS TURCOS'],
            ['codi_actividad'=>'41406','desc_actividad'=>'GIMNASIO'],
            ['codi_actividad'=>'41499','desc_actividad'=>'OTROS SERVICIOS DE HIGIENE Y ESTÉTICA PERSONAL NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'41501','desc_actividad'=>'FUNERARIAS'],
            ['codi_actividad'=>'41599','desc_actividad'=>'OTROS SERVICIOS PERSONALES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'42101','desc_actividad'=>'MECANOGRAFIADO'],
            ['codi_actividad'=>'42102','desc_actividad'=>'FOTOCOPIA DE DOCUMENTOS Y/O ENMICADOS'],
            ['codi_actividad'=>'42103','desc_actividad'=>'FRAGMENTACION Y/O EMBAZADO'],
            ['codi_actividad'=>'42104','desc_actividad'=>'ROTULACION'],
            ['codi_actividad'=>'42105','desc_actividad'=>'FUMIGACION'],
            ['codi_actividad'=>'42106','desc_actividad'=>'AGENCIAS DE PUBLICACION'],
            ['codi_actividad'=>'42107','desc_actividad'=>'PROCESAMIENTO ELECTRONICO DE DATOS'],
            ['codi_actividad'=>'42108','desc_actividad'=>'ESTUDIO FOTOGRAFICO'],
            ['codi_actividad'=>'42109','desc_actividad'=>'DECORACIONES'],
            ['codi_actividad'=>'42110','desc_actividad'=>'INSTALACIONES INDUSTRIALES Y COMERCIALES'],
            ['codi_actividad'=>'42111','desc_actividad'=>'GALVANOPLASTIA'],
            ['codi_actividad'=>'42112','desc_actividad'=>'CERRAJERIA'],
            ['codi_actividad'=>'42113','desc_actividad'=>'TORNERIA'],
            ['codi_actividad'=>'42114','desc_actividad'=>'SERVICIOS TECNICOS DE ASESORIA E INVESTIGACION DE MERCADOS'],
            ['codi_actividad'=>'42115','desc_actividad'=>'SERVICIOS GRAFICOS'],
            ['codi_actividad'=>'42199','desc_actividad'=>'OTROS SERVICIOS TECNICOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'43101','desc_actividad'=>'ALINEAMIENTO DE DIRECCIÓN Y/O BALANCEO DE RUEDAS'],
            ['codi_actividad'=>'43102','desc_actividad'=>'FACTORIA'],
            ['codi_actividad'=>'43103','desc_actividad'=>'LAVADO Y ENGRASE DE VEHÍCULOS'],
            ['codi_actividad'=>'43104','desc_actividad'=>'RECTIFICACION DE MOTORES'],
            ['codi_actividad'=>'43105','desc_actividad'=>'TALLER DE REPARACIONES ELECTRICAS DE VEHICULOS AUTOMOTORES'],
            ['codi_actividad'=>'43106','desc_actividad'=>'TALLER DE MECANICA AUTOMOTRIZ'],
            ['codi_actividad'=>'43107','desc_actividad'=>'TALLER DE REPARACIÓN DE BICICLETAS Y/O MOTOCICLETAS'],
            ['codi_actividad'=>'43108','desc_actividad'=>'CARROCERIAS'],
            ['codi_actividad'=>'43109','desc_actividad'=>'TALLER DE PLANCHADO Y PINTURA'],
            ['codi_actividad'=>'43110','desc_actividad'=>'VULCANIZADORA Y/O REENCAUCHADORA'],
            ['codi_actividad'=>'43111','desc_actividad'=>'TALLER DE BATERIAS'],
            ['codi_actividad'=>'43112','desc_actividad'=>'REPARACION DE EMBARCACIONES PESQUERAS'],
            ['codi_actividad'=>'43113','desc_actividad'=>'INSTALACIÓN DE TUBOS DE ESCAPE Y AFINES'],
            ['codi_actividad'=>'43199','desc_actividad'=>'OTROS SERVICIOS DE MECANICA AUTOMOTRIZ Y AFINES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'43201','desc_actividad'=>'TALLER DE SOLDADURA'],
            ['codi_actividad'=>'43202','desc_actividad'=>'TALLER DE REPARACION DE MAQUINARIA EN GENERAL'],
            ['codi_actividad'=>'43203','desc_actividad'=>'INSTALACIONES ELECTRICAS Y/O ELECTRONICAS'],
            ['codi_actividad'=>'43204','desc_actividad'=>'OTROS SERVICIOS DE MECANICA EN GENERAL Y ELECTRICIDAD NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'43301','desc_actividad'=>'TALLER DE REPARACION DE APARATOS DOMESTICOS ELECTRICOS'],
            ['codi_actividad'=>'43302','desc_actividad'=>'TALLER DE REPARACION DE APARATOS DE RADIO Y TELEVISION'],
            ['codi_actividad'=>'43303','desc_actividad'=>'TALLER DE REPARACION DE APARATOS DOMESTICOS MECANICOS'],
            ['codi_actividad'=>'43304','desc_actividad'=>'CARPINTERIA METALICA'],
            ['codi_actividad'=>'43306','desc_actividad'=>'TAPICERIA'],
            ['codi_actividad'=>'43307','desc_actividad'=>'GASFITERIA'],
            ['codi_actividad'=>'43308','desc_actividad'=>'REPARACIÓN DE CATRES Y SIMILARES'],
            ['codi_actividad'=>'43399','desc_actividad'=>'REPARACIÓN DE OTROS APARATOS DOMÉSTICOS NO ESPECIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'43401','desc_actividad'=>'TALLER DE MECANICA DE PRECISION'],
            ['codi_actividad'=>'43402','desc_actividad'=>'TALLER DE RELOJES'],
            ['codi_actividad'=>'43403','desc_actividad'=>'TALLER DE REPARACIONES DE JOYAS'],
            ['codi_actividad'=>'43499','desc_actividad'=>'OTROS SERVICIOS DE MECANICA FINA NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'44101','desc_actividad'=>'TRANSPORTE FERROVIARIO'],
            ['codi_actividad'=>'44102','desc_actividad'=>'TRANSPORTE URBANO'],
            ['codi_actividad'=>'44103','desc_actividad'=>'OTROS SERVICIOS TERRESTRES DE TRANSPORTE DE PASAJEROS'],
            ['codi_actividad'=>'44104','desc_actividad'=>'TRANSPORTE DE CARGA POR CARRETERA'],
            ['codi_actividad'=>'44105','desc_actividad'=>'TRANSPORTE POR OLEODUCTOS O GASEODUCTOS'],
            ['codi_actividad'=>'44106','desc_actividad'=>'SERVICIOS RELACIONADOS CON EL TRANSPORTE TERRESTRE'],
            ['codi_actividad'=>'44107','desc_actividad'=>'SILOS'],
            ['codi_actividad'=>'44199','desc_actividad'=>'OTROS SERVICIOS DE TRANSPORTE TERRESTRE NO ESPECIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'44201','desc_actividad'=>'TRANSPORTE OCEANICO O DE CABOTAJE'],
            ['codi_actividad'=>'44202','desc_actividad'=>'TRANSPORTE POR VIAS DE NAVEGACION INTERIOR'],
            ['codi_actividad'=>'44203','desc_actividad'=>'ESTIBADORES'],
            ['codi_actividad'=>'44204','desc_actividad'=>'SERVICIOS RELACIONADOS CON EL TRANSPORTE DE AGUA'],
            ['codi_actividad'=>'44299','desc_actividad'=>'OTROS SERVICIOS DE TRANSPORTE AÉREO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'44301','desc_actividad'=>'EMPRESAS DE TRANSPORTE AEREO'],
            ['codi_actividad'=>'44302','desc_actividad'=>'SERVICIOS RELACIONADOS CON EL TRANSPORTE AEREO'],
            ['codi_actividad'=>'44399','desc_actividad'=>'OTROS SERVICIOS DE TRANSPORTE AÉREO'],
            ['codi_actividad'=>'44401','desc_actividad'=>'SERVICIOS RELACIONADOS CON EL TRANSPORTE'],
            ['codi_actividad'=>'44402','desc_actividad'=>'DEPÓSITO Y ALMACENAMIENTO'],
            ['codi_actividad'=>'44499','desc_actividad'=>'OTROS SERVICIOS CONEXOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'44501','desc_actividad'=>'COMUNICACIONES'],
            ['codi_actividad'=>'44502','desc_actividad'=>'OTROS SERVICIOS CONEXOS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'45101','desc_actividad'=>'BANCO'],
            ['codi_actividad'=>'45102','desc_actividad'=>'AGENCIA BANCARIA'],
            ['codi_actividad'=>'45103','desc_actividad'=>'CAJA DE AHORRO'],
            ['codi_actividad'=>'45104','desc_actividad'=>'MUTUAL'],
            ['codi_actividad'=>'45105','desc_actividad'=>'COOPERATIVA DE CREDITO'],
            ['codi_actividad'=>'45106','desc_actividad'=>'CASA DE PRÉSTAMOS'],
            ['codi_actividad'=>'45199','desc_actividad'=>'OTRAS INSTITUCIONES MONETARIAS NO CLASIFICADAS EN OTRA PARTE'],
            ['codi_actividad'=>'45201','desc_actividad'=>'FINANCIERAS'],
            ['codi_actividad'=>'45202','desc_actividad'=>'BOLSA DE VALORES'],
            ['codi_actividad'=>'45203','desc_actividad'=>'AGENCIAS CAMBIARIAS'],
            ['codi_actividad'=>'45204','desc_actividad'=>'COMPAÑÍA DE PATENTES Y LICENCIAS'],
            ['codi_actividad'=>'45205','desc_actividad'=>'SERVICIOS FINANCIEROS'],
            ['codi_actividad'=>'45299','desc_actividad'=>'OTROS SERVICIOS DE ESTABLECIMIENTOS FINANCIEROS NO CLASIFICADOS EN  OTRA PARTE'],
            ['codi_actividad'=>'45301','desc_actividad'=>'SEGUROS'],
            ['codi_actividad'=>'45399','desc_actividad'=>'OTROS SERVICIOS DE SEGUROS NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'45401','desc_actividad'=>'SERVICIOS JURIDICOS'],
            ['codi_actividad'=>'45402','desc_actividad'=>'SERVICIOS DE CONTABILIDAD'],
            ['codi_actividad'=>'45403','desc_actividad'=>'SERVICIOS DE ELABORACION DE DATOS Y DE TABULACION'],
            ['codi_actividad'=>'45404','desc_actividad'=>'SERVICIOS TECNICOS Y ARQUITECTENICOS'],
            ['codi_actividad'=>'45405','desc_actividad'=>'SERVICIOS DE PUBLICIDAD'],
            ['codi_actividad'=>'45406','desc_actividad'=>'AGENCIA COMISIONISTA'],
            ['codi_actividad'=>'45407','desc_actividad'=>'COBRANZAS Y/O MENSAJES'],
            ['codi_actividad'=>'45408','desc_actividad'=>'AGENCIA DE EMPLEOS'],
            ['codi_actividad'=>'45409','desc_actividad'=>'AGENCIAS DE TRÁMITES'],
            ['codi_actividad'=>'45499','desc_actividad'=>'SERVICIOS PRESTADOS A LAS EMPRESAS'],
            ['codi_actividad'=>'45501','desc_actividad'=>'ALQUILER Y ARRENDAMIENTO DE MAQUINARIA Y EQUIPO'],
            ['codi_actividad'=>'45599','desc_actividad'=>'OTROS SERVICIOS DE ALQUILER Y ARRENDAMIENTO DE MAQUINARIA Y EQUIPO NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'46101','desc_actividad'=>'SERVICIOS DE SANEAMIENTO Y SIMILARES'],
            ['codi_actividad'=>'46102','desc_actividad'=>'OTROS SERVICIOS DE SANEAMIENTO Y SIMILARES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'46201','desc_actividad'=>'SERVICIOS MÉDICOS Y ODONTOLÓGICOS Y OTROS SERVICIOS DE SANIDAD'],
            ['codi_actividad'=>'46202','desc_actividad'=>'SERVICIOS DE VETERINARIA'],
            ['codi_actividad'=>'46203','desc_actividad'=>'ASOCIACIONES COMERCIALES'],
            ['codi_actividad'=>'46299','desc_actividad'=>'OTROS SERVICIOS SOCIALES Y COMUNALES NO CLASIFICADOS EN OTRA PARTE'],
            ['codi_actividad'=>'46301','desc_actividad'=>'PRODUCCION DE PELICULAS CINEMATOGRAFICAS'],
            ['codi_actividad'=>'46302','desc_actividad'=>'DISTRIBUCION Y EXHIBICION DE PELICULAS CINEMATOGRAFICAS'],
            ['codi_actividad'=>'46303','desc_actividad'=>'EMISION DE RADIO Y TELEVISION'],
            ['codi_actividad'=>'46304','desc_actividad'=>'PRODUCTORES TEATRALES Y SERVICIOS DE ESPARCIMIENTO'],
            ['codi_actividad'=>'46305','desc_actividad'=>'AUTORES'],
            ['codi_actividad'=>'46306','desc_actividad'=>'BIBLIOTECAS'],
            ['codi_actividad'=>'46307','desc_actividad'=>'SERVICIOS DE DIVERSION Y ESPARCIMIENTO'],
            ['codi_actividad'=>'46308','desc_actividad'=>'ALQUILER DE APARATOS É INSTRUMENTOS MUSICALES'],
            ['codi_actividad'=>'46309','desc_actividad'=>'CENTROS DE COMPETENCIAS Y/O APUESTAS'],
            ['codi_actividad'=>'46310','desc_actividad'=>'CENTROS NOCTURNOS'],
            ['codi_actividad'=>'46311','desc_actividad'=>'CABARET'],
            ['codi_actividad'=>'46312','desc_actividad'=>'DISCOTECA'],
            ['codi_actividad'=>'46313','desc_actividad'=>'BOITE'],
            ['codi_actividad'=>'46314','desc_actividad'=>'COLISEOS'],
            ['codi_actividad'=>'46315','desc_actividad'=>'SALON DE JUEGOS'],
            ['codi_actividad'=>'46316','desc_actividad'=>'SERVICIOS PARA FIESTAS'],
            ['codi_actividad'=>'46317','desc_actividad'=>'CAFÉ-TEATROS'],
            ['codi_actividad'=>'46318','desc_actividad'=>'PEÑA CRIOLLA'],
            ['codi_actividad'=>'46319','desc_actividad'=>'CASAS DE CITAS'],
            ['codi_actividad'=>'46320','desc_actividad'=>'PROSTIBULOS'],
            ['codi_actividad'=>'46322','desc_actividad'=>'ALQUILER DE VIDEOS (V.H.S.)'],
            ['codi_actividad'=>'46323','desc_actividad'=>'VIDEOS JUEGOS (NINTENDO)'],
            ['codi_actividad'=>'46324','desc_actividad'=>'VIDEO PUB'],
            ['codi_actividad'=>'46327','desc_actividad'=>'PUB'],
            ['codi_actividad'=>'46330','desc_actividad'=>'TALLER ARTES PLÁSTICAS'],
            ['codi_actividad'=>'46399','desc_actividad'=>'OTROS SERVICIOS DE DIVERSIÓN'],
            ['codi_actividad'=>'46400','desc_actividad'=>'EDUCACION'],
        ];

        foreach ($actividades as $actividad) {
            Actividades::create($actividad);
        }
    }
}
