<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TablaCodigo; 



class TablaCodigosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $tablas = [                        
            ['codigo'=>'01'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'TITULO DE PROPIEDAD'],
            ['codigo'=>'02'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE COMPRA-VENTA'],
            ['codigo'=>'05'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE PRESTAMO CON INSTITUCIONES'],
            ['codigo'=>'11'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE DEFUNCION'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'INVITADO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'CONTROL CALIDAD DISTRITAL'],
            ['codigo'=>'07'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'PROGRAMACION GENERAL'],
            ['codigo'=>'08'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'SUPERVISION'],
            ['codigo'=>'09'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'PROGRAMACION POR AREA'],
            ['codigo'=>'01'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'GESTION CONVENIOS'],
            ['codigo'=>'02'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'ELABORACION MOSAICO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'LEVANTAMIENTO TOPOGRAFICO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'LEVANTAMIENTO CATASTRAL'],
            ['codigo'=>'10'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'EDICION GRAFICA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'DIGITACION FICHAS CATASTRALES'],
            ['codigo'=>'09'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'PUESTO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'STAND'],
            ['codigo'=>'09'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DNI'],
            ['codigo'=>'13'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE MATRIMONIO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DOC. DE TRANFERENCIA'],
            ['codigo'=>'15'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PODERES'],
            ['codigo'=>'01'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL OMISO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL SUBVALUADO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL SOBREVALUADO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL CONFORME'],
            ['codigo'=>'011'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO VARIABLE'],
            ['codigo'=>'012'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO LUMINOSO'],
            ['codigo'=>'013'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO DE PROYECCION'],
            ['codigo'=>'014'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO ILUMINADO'],
            ['codigo'=>'021'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL VARIABLE'],
            ['codigo'=>'022'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL LUMINOSO'],
            ['codigo'=>'023'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL DE PROYECCION'],
            ['codigo'=>'024'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL ILUMINADO'],
            ['codigo'=>'031'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA VARIABLE'],
            ['codigo'=>'032'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA LUMINOSO'],
            ['codigo'=>'033'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA DE PROYECCION'],
            ['codigo'=>'034'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA ILUMINADO'],
            ['codigo'=>'041'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO VARIABLE'],
            ['codigo'=>'042'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO LUMINOSO'],
            ['codigo'=>'043'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO DE PROYECCION'],
            ['codigo'=>'044'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO ILUMINADO'],
            ['codigo'=>'051'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO VARIABLE'],
            ['codigo'=>'052'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO LUMINOSO'],
            ['codigo'=>'053'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO DE PROYECCION'],
            ['codigo'=>'054'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO ILUMINADO'],
            ['codigo'=>'061'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS VARIABLE'],
            ['codigo'=>'062'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS LUMINOSO'],
            ['codigo'=>'063'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS DE PROYECCION'],
            ['codigo'=>'064'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS ILUMINADO'],
            ['codigo'=>'071'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA VARIABLE'],
            ['codigo'=>'072'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA LUMINOSO'],
            ['codigo'=>'073'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA DE PROYECCION'],
            ['codigo'=>'074'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA ILUMINADO'],
            ['codigo'=>'081'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE VARIABLE'],
            ['codigo'=>'082'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE LUMINOSO'],
            ['codigo'=>'083'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE DE PROYECCION'],
            ['codigo'=>'084'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE ILUMINADO'],
            ['codigo'=>'091'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL VARIABLE'],
            ['codigo'=>'092'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL LUMINOSO'],
            ['codigo'=>'093'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL DE PROYECCION'],
            ['codigo'=>'094'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL ILUMINADO'],
            ['codigo'=>'101'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES VARIABLE'],
            ['codigo'=>'102'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES LUMINOSO'],
            ['codigo'=>'103'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES DE PROYECCION'],
            ['codigo'=>'104'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES ILUMINADO'],
            ['codigo'=>'111'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS VARIABLE'],
            ['codigo'=>'112'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS LUMINOSO'],
            ['codigo'=>'113'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS DE PROYECCION'],
            ['codigo'=>'114'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS ILUMINADO'],
            ['codigo'=>'121'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS VARIABLE'],
            ['codigo'=>'122'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS LUMINOSO'],
            ['codigo'=>'123'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS DE PROYECCION'],
            ['codigo'=>'124'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS ILUMINADO'],
            ['codigo'=>'131'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO VARIABLE'],
            ['codigo'=>'132'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO LUMINOSO'],
            ['codigo'=>'133'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO DE PROYECCION'],
            ['codigo'=>'134'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO ILUMINADO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'AAHH'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'ASENTAMIENTO HUMANO'],
            ['codigo'=>'17'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'PENSIONISTA'],
            ['codigo'=>'AGRUP'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'AGRUPACION'],
            ['codigo'=>'C.H.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'CONJUNTO HABITACIONAL'],
            ['codigo'=>'C.R.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'CONJUNTO RESIDENCIAL'],
            ['codigo'=>'P.J.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'PUEBLO JOVEN'],
            ['codigo'=>'URB'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'URBANIZACION'],
            ['codigo'=>'URB.PP'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'URBANIZACION POPULAR'],
            ['codigo'=>'CRCADO'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'CERCADO'],
            ['codigo'=>'HACIND'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'HACIENDA'],
            ['codigo'=>'ASOC'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'ASOCIACION'],
            ['codigo'=>'COOP'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'COOPERATIVA'],
            ['codigo'=>'LOTIZ'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'LOTIZACION'],
            ['codigo'=>'PARCLA'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'PARCELA'],
            ['codigo'=>'VALLE'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'VALLE'],
            ['codigo'=>'CASRIO'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'CASERIO'],
            ['codigo'=>'U.V.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'UNIDAD VECINAL'],
            ['codigo'=>'COMUN'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'COMUNIDAD'],
            ['codigo'=>'BARRIO'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'BARRIO'],
            ['codigo'=>'FUNDO'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'FUNDO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'DFB'	,'desc_codigo'=>'FABRICA INSCRITA'],
            ['codigo'=>'AS.VI'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'ASOCIACION DE VIVIENDA'],
            ['codigo'=>'COOP.V'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'COOPERATIVA DE VIVIENDA'],
            ['codigo'=>'AS.PV'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'ASOCIACION PRO VIVIENDA'],
            ['codigo'=>'C.P.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'CENTRO POBLADO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'DFB'	,'desc_codigo'=>'FABRICA NO INSCRITA'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'TITULAR CATASTRAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'ARRENDATARIO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'CESION EN USO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'TITULAR CATASTRAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'REPRESENTANTE LEGAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'ARRENDATARIO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'FAMILIAR'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CASA HABITACION'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TIENDA / DEPOSITO / ALMACEN'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PREDIO EN EDIFICIO'],
            ['codigo'=>'041'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLINICA'],
            ['codigo'=>'0410'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CEMENTERIO'],
            ['codigo'=>'0411'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'SUB ESTACION'],
            ['codigo'=>'0412'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'BANCO FINANCIERA'],
            ['codigo'=>'0413'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TERMINAL DE TRANSPORTE'],
            ['codigo'=>'0414'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'MERCADO'],
            ['codigo'=>'0415'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLUB SOCIAL'],
            ['codigo'=>'0416'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLUB DE ESPARCIMIENTO'],
            ['codigo'=>'0417'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PLAYA DE ESTACIONAMIENTO'],
            ['codigo'=>'042'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'HOSPITAL'],
            ['codigo'=>'043'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CINE / TEATRO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'13'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'POSESIÓN'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'VECINO'],
            ['codigo'=>'044'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'INDUSTRIA'],
            ['codigo'=>'045'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TALLER'],
            ['codigo'=>'046'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'IGLESIA / TEMPLO'],
            ['codigo'=>'047'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CENTRO DE ENSEÑANZA'],
            ['codigo'=>'048'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'SERVICIO DE COMIDA'],
            ['codigo'=>'049'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PARQUE'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TERRENO SIN CONSTRUIR'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'MONUMENTO HISTORICO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'PREDIO RUSTICO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'SISTEMA DE AYUDA DE AERONAVEGACION'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO CENTRAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO LOCAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO REGIONAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'BENEFICENCIA PUBLICA'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'HOSPITALES'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ENTIDADES RELIGIOSAS'],
            ['codigo'=>'07'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'CUERPO GENERAL DE BOMBEROS'],
            ['codigo'=>'08'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'UNIVERSIDADES'],
            ['codigo'=>'09'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'CENTRO EDUCATIVO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'COMUNIDAD CAMPESINA / NATIVA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANISMOS INTERNACIONALES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO EXTRANJERO'],
            ['codigo'=>'13'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACION POLITICA'],
            ['codigo'=>'14'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'PATRIMONIO CULTURAL DE LA NACION'],
            ['codigo'=>'15'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACIONES SINDICALES'],
            ['codigo'=>'16'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACIONES DE DISCAPACITADOS'],
            ['codigo'=>'17'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'PENSIONISTA'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'GENERADO POR MUNICIPALIDAD'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'AUTOGENERADO POR EL TITULAR CAT.'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'GENERADO POR EL TÉCNICO CAT.'],
            ['codigo'=>'01'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE FUNCIONAMIENTO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE ANUNCIOS'],
            ['codigo'=>'03'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE FUNCIONAMIENTO Y ANUNCIOS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'NO PRESENTO DOCUMENTO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'DNI'],
            ['codigo'=>'03'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE IDENTIDAD DE POLICIA NACIONAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE IDENTIDAD DE FUERZAS ARMADAS'],
            ['codigo'=>'05'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'PASAPORTE'],
            ['codigo'=>'07'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE EXTRANJERIA'],
            ['codigo'=>'01'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'TERMINADO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'EN CONSTRUCCION'],
            ['codigo'=>'03'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'INCONCLUSA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'EN RUINAS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'MUY BUENO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'BUENO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'REGULAR'],
            ['codigo'=>'04'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'MALO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'SOLTERO(A)'],
            ['codigo'=>'02'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'CASADO(A)'],
            ['codigo'=>'03'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'DIVORCIADO(A)'],
            ['codigo'=>'04'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'VIUDO(A)'],
            ['codigo'=>'05'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'CONVIVIENTE'],
            ['codigo'=>'01'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'COMPRA VENTA'],
            ['codigo'=>'02'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'ANTICIPO LEGITIMA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'TESTAMENTO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DONACION'],
            ['codigo'=>'05'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'ADJUDICACION'],
            ['codigo'=>'06'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'FUSION'],
            ['codigo'=>'07'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'EXPROPIACION'],
            ['codigo'=>'08'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'PERMUTA'],
            ['codigo'=>'09'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'PRESCRIPCION ADQUISITIVA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'CESION DE DERECHOS DE ACCIONES'],
            ['codigo'=>'11'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DACION EN PAGO'],
            ['codigo'=>'12'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DECLARACION DE HEREDEROS'],
            ['codigo'=>'1'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'FICHA COMPLETA'],
            ['codigo'=>'2'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'FICHA INCOMPLETA'],
            ['codigo'=>'3'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'COMPLETADA EN OFICINA'],
            ['codigo'=>'4'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'COMPLETADA EN CONTROL EXTERIOR'],
            ['codigo'=>'1'	        ,'id_tabla'=>'LOG'	,'desc_codigo'=>'SI'],
            ['codigo'=>'2'	        ,'id_tabla'=>'LOG'	,'desc_codigo'=>'NO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'CONCRETO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'LADRILLO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'ADOBE(QUINCHA'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION DE UNIDADES'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION EN LA CONSTRUCCION'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION DE PORCENTAJE'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR CAMBIO DE USO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR SER PREDIO CATASTRAL NUEVO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR TENER VARIACION EN AREA DE USO'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR CAMBIO DE CONDUCTOR'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR CAMBIO DE GIRO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR SER PREDIO CATASTRAL NUEVO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR VARIACION EN LA CONSTRUCCION'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR CAMBIO DEL TITULAR CATASTRAL'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR CAMBIO DE USO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'GALERIA'],
            ['codigo'=>'02'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'MERCADO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CAMPO FERIAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CENTRO COMERCIAL'],
            ['codigo'=>'05'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'QUINTA'],
            ['codigo'=>'06'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CALLEJON'],
            ['codigo'=>'07'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'PREDIO INDEPENDIENTE'],
            ['codigo'=>'08'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'SOLAR'],
            ['codigo'=>'09'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CORRALON'],
            ['codigo'=>'10'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'AZOTEA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'AIRES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'PREDIO EN EDIFICIO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CONFORMIDAD DE OBRA'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'LICENCIA DE CONSTRUCCION'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'DECLARATORIA DE FÁBRICA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'ULTIMA DECLARACION JURADA AUTOAVALUO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'RESOLUCION DE EXONERACION'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PODERES'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'BLOCK'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'EDIFICIO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'PABELLON'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'DEPARTAMENTO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'OFICINA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'DEPOSITO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'TENDAL'],
            ['codigo'=>'07'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'TIENDA'],
            ['codigo'=>'08'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'PUESTO'],
            ['codigo'=>'09'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'STAND'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'TOMO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'FICHA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'PARTIDA ELECTRONICA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'CÓDIGO DE PREDIO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'EMPRESA'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'COOPERATIVA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'ASOCIACION'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'FUNDACION'],
            ['codigo'=>'E'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'G'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'GARAGE'],
            ['codigo'=>'P'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'PRINCIPAL'],
            ['codigo'=>'S'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'SECUNDARIO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'TPE'	,'desc_codigo'=>'PERSONA NATURAL'],
            ['codigo'=>'2'	        ,'id_tabla'=>'TPE'	,'desc_codigo'=>'PERSONA JURIDICA'],
            ['codigo'=>'01'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN RETIRO MUNICIPAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN JARDÍN DE AISLAMIENTO'],
            ['codigo'=>'03'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN VIA PUBLICA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN LOTE COLINDANTE'],
            ['codigo'=>'05'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'ALTURA NO REGLAMENTARIA'],
            ['codigo'=>'06'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN PARQUE'],
            ['codigo'=>'AL'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'ALAMEDA'],
            ['codigo'=>'AV'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'AVENIDA'],
            ['codigo'=>'CA'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CALLE'],
            ['codigo'=>'CAM'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CAMINO'],
            ['codigo'=>'CTRA'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CARRETERA'],
            ['codigo'=>'JR'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'JIRON'],
            ['codigo'=>'ML'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'MALECON'],
            ['codigo'=>'PJE'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PASAJE'],
            ['codigo'=>'PRLG'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PROLONGACION'],
            ['codigo'=>'PS'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PASEO'],
            ['codigo'=>'00'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'RUC'],
            ['codigo'=>'01'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA INDIVIDUAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA COTITULARIDAD'],
            ['codigo'=>'03'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA ACTIVIDAD ECONOMICA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA BIENES COMUNES'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'DIGITADOR(A)'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'SUPERVISOR(A)'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'TÉCNICO(A) CATASTRAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'VERIFICADOR(A) CATASTRAL'],
            ['codigo'=>'G.R.'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'GRUPO RESIDENCIAL'],
            ['codigo'=>'00'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'ADMINISTRADOR'],
            ['codigo'=>'0418'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'07'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'ENCARGADO'],
            ['codigo'=>'08'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN ZONA DE RIESGO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO CENTRAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO LOCAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO REGIONAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'BENEFICENCIA PUBLICA'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'HOSPITALES'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ENTIDADES RELIGIOSAS'],
            ['codigo'=>'07'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'CUERPO GENERAL DE BOMBEROS'],
            ['codigo'=>'08'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'UNIVERSIDADES'],
            ['codigo'=>'09'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'CENTRO EDUCATIVO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'COMUNIDAD CAMPESINA / NATIVA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANISMOS INTERNACIONALES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO EXTRANJERO'],
            ['codigo'=>'13'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACION POLITICA'],
            ['codigo'=>'14'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'PATRIMONIO CULTURAL DE LA NACION'],
            ['codigo'=>'15'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACIONES SINDICALES'],
            ['codigo'=>'16'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACIONES DE DISCAPACITADOS'],
            ['codigo'=>'12'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'DEPARTAMENTO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'OFICINA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'DEPOSITO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'TENDAL'],
            ['codigo'=>'07'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'TIENDA'],
            ['codigo'=>'16'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'RUT01'	    ,'id_tabla'=>'RUT'	,'desc_codigo'=>'RUTA PLANO PROPIEDADES'],
            ['codigo'=>'S/T'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'SIN TIPO'],
            ['codigo'=>'HABCOM'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'HABILITACIÓN COMERCIAL'],
            ['codigo'=>'OJ'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'GGG'],
            ['codigo'=>'08'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'AIRES'],
            ['codigo'=>'03'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONSTANCIA DE POSESION'],
            ['codigo'=>'04'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'06'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CLAUSULA DE CANCELACION'],
            ['codigo'=>'07'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DECLARATORIA DE FÁBRICA'],
            ['codigo'=>'08'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'RECIBO DE LUZ  AGUA Y OTROS SERVICIO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE ALQUILER'],
            ['codigo'=>'1'	        ,'id_tabla'=>'ECH'	,'desc_codigo'=>'REGISTRADO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'ECH'	,'desc_codigo'=>'REVISADO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'PROPIETARIO UNICO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'POSEEDOR'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'SOCIEDAD CONYUGAL'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'COTITULARIDAD'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'LITIGIO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'PROPIETARIO UNICO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'POSEEDOR'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'SOCIEDAD CONYUGAL'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'COTITULARIDAD'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'LITIGIO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'SIN DATOS'],
            ['codigo'=>'06'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'SIN DATOS'],
            ['codigo'=>'04'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'FIERRO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'ROTOPLAS'],
            ['codigo'=>'06'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'POLICARBONATO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'08'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'09'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'LIBRETA MILITAR'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'GOBIERNO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'13'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'08'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'POSEEDOR'],
            ['codigo'=>'H.U.PR'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'HABILITACIÓN URBANO PROGRESIVA'],
            ['codigo'=>'AMP.PJ'	,'id_tabla'=>'HUR'	,'desc_codigo'=>'AMPLIACION PUEBLO JOVEN'],
            ['codigo'=>'UPIS'	    ,'id_tabla'=>'HUR'	,'desc_codigo'=>'URBANIZACION POPULAR DE INTERES SOCIAL'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION RESIDENCIAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION COMERCIAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION INDUSTRIAL'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION OTROS USOS'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION REGLAMENTACION ESPECIAL'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION OTROS'],
            ['codigo'=>'07'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION EQUIPAMIENTOS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'PATRIMONIO MUNDIAL'],
            ['codigo'=>'02'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ZONA ARQUEOLOGICA MONUMENTAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'SITIO ARQUEOLOGICO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ZONA DE RESERVA ARQUEOLOGICA'],
            ['codigo'=>'05'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ELEMENTO ARQUEOLOGICO AISLADO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'PAISAJE CULTURAL ARQUEOLOGICO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'PRE-CERAMICO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'PERIODO INICIAL'],
            ['codigo'=>'03'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE TEMPRANO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INTERMEDIO TEMPRANO'],
            ['codigo'=>'05'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE MEDIO'],
            ['codigo'=>'06'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INTERMEDIO TARDIO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE TARDIO'],
            ['codigo'=>'08'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'VARIOS PERIODOS'],
            ['codigo'=>'09'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INDETERMINADO'],
            ['codigo'=>'01'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'CIVIL PUBLICA'],
            ['codigo'=>'02'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'CIVIL DOMESTICA'],
            ['codigo'=>'03'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'RELIGIOSA'],
            ['codigo'=>'04'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'MILITAR'],
            ['codigo'=>'05'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'INDUSTRIAL'],
            ['codigo'=>'06'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'FUNERARIA'],
            ['codigo'=>'07'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'GOTICO'],
            ['codigo'=>'02'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'MUDEJAR'],
            ['codigo'=>'03'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'PLATERESCO'],
            ['codigo'=>'04'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'RENACENTISTA'],
            ['codigo'=>'05'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'MANIERISTA'],
            ['codigo'=>'06'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'BARROCO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ROCOCO'],
            ['codigo'=>'08'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOCLASICO'],
            ['codigo'=>'09'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEORENACENTISTA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ACADEMICISTA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ART NOUVEAU'],
            ['codigo'=>'12'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOCOLONIAL'],
            ['codigo'=>'13'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOPERUANO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'INDIGENISTA'],
            ['codigo'=>'15'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ART DECO'],
            ['codigo'=>'16'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'01'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'AMPLIACION'],
            ['codigo'=>'02'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'ANASTILOSIS'],
            ['codigo'=>'03'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSERVACION'],
            ['codigo'=>'04'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSOLIDACION'],
            ['codigo'=>'05'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSTRUCCION'],
            ['codigo'=>'06'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'DEMOLICION'],
            ['codigo'=>'07'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'RENOVACION URBANA O REVITALIZACION URBANA'],
            ['codigo'=>'08'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'PROTECCION'],
            ['codigo'=>'09'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'PUESTA EN VALOR'],
            ['codigo'=>'10'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'REFACCION'],
            ['codigo'=>'11'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'REMODELACION'],
            ['codigo'=>'12'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'OBRA NUEVA'],
            ['codigo'=>'13'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'RESTAURACION'],
            ['codigo'=>'07'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN BIEN COMUN'],
            ['codigo'=>'04'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'SIN NUMERO'],
            ['codigo'=>'07'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'ESCRITURA PUBLICA'],
            ['codigo'=>'08'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'MINUTA COMPRA VENTA'],
            ['codigo'=>'09'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'DOCUMENTO DE TRANSFERENCIA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CONSTANCIA DE POSESION'],
            ['codigo'=>'11'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PARTIDA DE DEFUNCION'],
            ['codigo'=>'12'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CERTIFICADO CATASTRAL'],
            ['codigo'=>'13'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'HOJA INFORMATIVA CATASTRAL'],
            ['codigo'=>'14'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'C-7'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-7 COMERCIO ZONAL'],
            ['codigo'=>'I1-R5'  ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'I1-R5 VIVIENDA TALLER DE ALTA DENSIDAD'],
            ['codigo'=>'E1'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'E1 EDUCACION BASICA'],
            ['codigo'=>'R-5'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'R-5 RESIDENCIAL DE DENSIDAD MEDIA'],
            ['codigo'=>'OU'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'OU OTROS USOS'],
            ['codigo'=>'C-5'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-5 COMERCIO ESPECIALIZADO'],
            ['codigo'=>'ZRP1'   ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'ZRP1 ZONA DE RECREACION BARRIAL'],
            ['codigo'=>'E2'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'E2 EDUCACION SUPERIOR TECNOLOGICO'],
            ['codigo'=>'C-3'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-3 COMERCIO VECINAL'],
            ['codigo'=>'R-4'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'R-4 RESIDENCIAL DE DENSIDAD MEDIA'],
            ['codigo'=>'H1'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'H1 POSTA MEDICA'],
            ['codigo'=>'ZAM-CH' ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'ZAM-CH AREA DE AMORTIGUAMIENTO'],
            ['codigo'=>'MER'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'MERCADO MERCADO'],
            ['codigo'=>'CH'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'CH CENTRO HISTORICO'],
            ['codigo'=>'AP'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'AP'],

        ];
        foreach ($tablas as $tabla) {
            TablaCodigo::create($tabla);
        }
    }
}
