<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Uso;



class UsosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $usos = [            
            
            ['codi_uso'=> '010201'	,'desc_uso'=>'EDIFICIO'],
            ['codi_uso'=> '010202'	,'desc_uso'=>'QUINTA'],
            ['codi_uso'=> '010205'	,'desc_uso'=>'SOLAR'],
            ['codi_uso'=> '020101'	,'desc_uso'=>'PRODUCTOS AGROPECUARIOS Y PESQUEROS NO INDUSTRIALIZADOS.'],
            ['codi_uso'=> '020102'	,'desc_uso'=>'PRODUCTOS DE SILVICULTURA'],
            ['codi_uso'=> '020103'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE CONSUMO INMEDIATO.'],
            ['codi_uso'=> '020104'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS DE USO DURADERO.'],
            ['codi_uso'=> '020105'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE INSUMOS'],
            ['codi_uso'=> '020106'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE BIENES DE CAPITAL.'],
            ['codi_uso'=> '020107'	,'desc_uso'=>'DE BIENES NO ESPECIFICADOS.'],
            ['codi_uso'=> '020201'	,'desc_uso'=>'PRODUCTOS AGROPECUARIOS Y PESQUEROS NO INDUSTRIALIZADOS.'],
            ['codi_uso'=> '020202'	,'desc_uso'=>'PRODUCTOS DE SILVICULTURA'],
            ['codi_uso'=> '020203'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE CONSUMO INMEDIATO.'],
            ['codi_uso'=> '020204'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS DE USO DURADERO.'],
            ['codi_uso'=> '020205'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE INSUMOS'],
            ['codi_uso'=> '020206'	,'desc_uso'=>'PRODUCTOS MANUFACTURADOS PREDOMINANTEMENTE DE BIENES DE CAPITAL.'],
            ['codi_uso'=> '020207'	,'desc_uso'=>'EQUIPAMIENTO DE COMERCIO AMBULATORIO.'],
            ['codi_uso'=> '020208'	,'desc_uso'=>'DE BIENES NO ESPECIFICADOS'],
            ['codi_uso'=> '020305'	,'desc_uso'=>'DE PRODUCTOS EN ESTADO NATURAL'],
            ['codi_uso'=> '020306'	,'desc_uso'=>'DE PRODUCTOS DERIVADOS NO INDUSTRIALIZADOS'],
            ['codi_uso'=> '020307'	,'desc_uso'=>'DE PRODUCTOS ALIMENTICIOS'],
            ['codi_uso'=> '020308'	,'desc_uso'=>'DE ALIMENTOS PREPARADOS PARA ANIMALES'],
            ['codi_uso'=> '020311'	,'desc_uso'=>'DE COMBUSTIBLES Y LUBRICANTES'],
            ['codi_uso'=> '020312'	,'desc_uso'=>'DE TELAS'],
            ['codi_uso'=> '020314'	,'desc_uso'=>'DE LIBROS'],
            ['codi_uso'=> '020318'	,'desc_uso'=>'DE FERTILIZANTES'],
            ['codi_uso'=> '020320'	,'desc_uso'=>'DE INSUMOS MANUFACTURADOS'],
            ['codi_uso'=> '020321'	,'desc_uso'=>'DE REPUESTOS Y ACCESORIOS'],
            ['codi_uso'=> '020322'	,'desc_uso'=>'DE MAQUINARIAS'],
            ['codi_uso'=> '020325'	,'desc_uso'=>'DE PRODUCTOS DE DIVERSAS RAMAS DEL MISMO RUBRO'],
            ['codi_uso'=> '020401'	,'desc_uso'=>'DE ESTUDIOS Y PROYECTOS'],
            ['codi_uso'=> '020404'	,'desc_uso'=>'ASESORES Y CONSULTORES'],
            ['codi_uso'=> '020406'	,'desc_uso'=>'DE CORRETAJE Y AFINES'],
            ['codi_uso'=> '020409'	,'desc_uso'=>'ADMINISTRATIVA'],
            ['codi_uso'=> '020503'	,'desc_uso'=>'DE VIVIENDA Y ALOJAMIENTO / HOTEL'],
            ['codi_uso'=> '020505'	,'desc_uso'=>'DE MANTENIMIENTO Y LIMPIEZA DE MUEBLES.'],
            ['codi_uso'=> '020511'	,'desc_uso'=>'PRESTADOS A LAS EMPRESAS.'],
            ['codi_uso'=> '020512'	,'desc_uso'=>'ALQUILER Y ARRENDAMIENTO DE MAQUINARIA Y EQUIPO.'],
            ['codi_uso'=> '020513'	,'desc_uso'=>'DE SANEAMIENTO Y SIMILARES.'],
            ['codi_uso'=> '020514'	,'desc_uso'=>'DE VETERINARIA.'],
            ['codi_uso'=> '020515'	,'desc_uso'=>'AGENCIAS DE TURISMO'],
            ['codi_uso'=> '020516'	,'desc_uso'=>'DE CABALLERIZA.'],
            ['codi_uso'=> '020517'	,'desc_uso'=>'DE ESPARCIMIENTO NO ESPECIFICADO.'],
            ['codi_uso'=> '030101'	,'desc_uso'=>'AGRICULTURA'],
            ['codi_uso'=> '030201'	,'desc_uso'=>'PRODUCTOS ALIMENTICIOS'],
            ['codi_uso'=> '030202'	,'desc_uso'=>'TEXTILES'],
            ['codi_uso'=> '030203'	,'desc_uso'=>'INDUSTRIA DE LA MADERA Y PRODUCTOS DE LA MADERA INCLUIDOS MUEBLES.'],
            ['codi_uso'=> '030209'	,'desc_uso'=>'OTRAS INDUSTRIAS MANUFACTURERAS NO ESPECIFICADAS.'],
            ['codi_uso'=> '040101'	,'desc_uso'=>'PARQUE METROPOLITANO.'],
            ['codi_uso'=> '040102'	,'desc_uso'=>'PARQUE ZONAL.'],
            ['codi_uso'=> '040103'	,'desc_uso'=>'PARQUE.'],
            ['codi_uso'=> '040104'	,'desc_uso'=>'ESTADIO.'],
            ['codi_uso'=> '040106'	,'desc_uso'=>'COLISEO.'],
            ['codi_uso'=> '040108'	,'desc_uso'=>'CENTRO DEPORTIVO.'],
            ['codi_uso'=> '040109'	,'desc_uso'=>'PISTA DE PATINAJE.'],
            ['codi_uso'=> '040110'	,'desc_uso'=>'CANCHA DE BOWLING.'],
            ['codi_uso'=> '040111'	,'desc_uso'=>'MESA DE BILLAR Y BILLAS.'],
            ['codi_uso'=> '040112'	,'desc_uso'=>'CANCHA DE BOCHAS'],
            ['codi_uso'=> '040113'	,'desc_uso'=>'GIMNASIO'],
            ['codi_uso'=> '040116'	,'desc_uso'=>'ACADEMIA DE DANZA'],
            ['codi_uso'=> '040117'	,'desc_uso'=>'ACADEMIA DE DEPORTES'],
            ['codi_uso'=> '040118'	,'desc_uso'=>'ACADEMIA DE ARTES MARCIALES'],
            ['codi_uso'=> '040119'	,'desc_uso'=>'PLAZOLETA'],
            ['codi_uso'=> '040201'	,'desc_uso'=>'MUSEO.'],
            ['codi_uso'=> '040202'	,'desc_uso'=>'CENTRO DE CONVENCIONES.'],
            ['codi_uso'=> '040205'	,'desc_uso'=>'TEATRO'],
            ['codi_uso'=> '040208'	,'desc_uso'=>'CINE.'],
            ['codi_uso'=> '040209'	,'desc_uso'=>'BIBLIOTECA.'],
            ['codi_uso'=> '040210'	,'desc_uso'=>'OBSERVATORIO'],
            ['codi_uso'=> '040301'	,'desc_uso'=>'DISCOTECA.'],
            ['codi_uso'=> '040302'	,'desc_uso'=>'BINGO'],
            ['codi_uso'=> '040303'	,'desc_uso'=>'PINBALL O SIMILAR.'],
            ['codi_uso'=> '040307'	,'desc_uso'=>'CENTRO DE APUESTA'],
            ['codi_uso'=> '010203'	,'desc_uso'=>'CALLEJON'],
            ['codi_uso'=> '010204'	,'desc_uso'=>'CORRALON'],
            ['codi_uso'=> '020301'	,'desc_uso'=>'DE PRODUCTOS AGRÍCOLAS COMESTIBLES'],
            ['codi_uso'=> '020303'	,'desc_uso'=>'DE ANIMALES GENERALMENTE NO UTILIZADOS EN LA ALIMETACION HUMANA'],
            ['codi_uso'=> '020304'	,'desc_uso'=>'DE ANIMALES GENERALMENTE UTILIZADOS EN LA ALIMENTACION HUMANA'],
            ['codi_uso'=> '020310'	,'desc_uso'=>'DE PRODUCTOS FARMACEUTICOS Y ARTÍCULOS DE TOCADOR'],
            ['codi_uso'=> '020313'	,'desc_uso'=>'DE ARTÍCULOS DEL HOGAR'],
            ['codi_uso'=> '020315'	,'desc_uso'=>'DE ARTÍCULOS ARTÍSTICOS Y DE LUJO'],
            ['codi_uso'=> '020316'	,'desc_uso'=>'DE AUTOMOVILES Y OTROS MEDIOS DE TRANSPORTE Y TRACCION PERSONAL'],
            ['codi_uso'=> '020317'	,'desc_uso'=>'DE DIVERSOS ARTÍCULOS DE USO DURADERO'],
            ['codi_uso'=> '020319'	,'desc_uso'=>'DE INSUMOS MANUFACTURADOS PARA LA INDUSTRIA DE TRANSFORMACION'],
            ['codi_uso'=> '020323'	,'desc_uso'=>'DE APARATOS DE MEDICION'],
            ['codi_uso'=> '040309'	,'desc_uso'=>'CIRCO'],
            ['codi_uso'=> '040310'	,'desc_uso'=>'KARAOKE'],
            ['codi_uso'=> '050116'	,'desc_uso'=>'OTRO NO ESPECIFICADO'],
            ['codi_uso'=> '050201'	,'desc_uso'=>'HOSPITAL ESPECIALIZADO'],
            ['codi_uso'=> '050202'	,'desc_uso'=>'HOSPITAL GENERAL'],
            ['codi_uso'=> '050203'	,'desc_uso'=>'HOSPITAL GENERAL DE LAS FUERZAS ARMADAS Y POLICIALES'],
            ['codi_uso'=> '050206'	,'desc_uso'=>'CENTRO DE SALUD TIPO C'],
            ['codi_uso'=> '050207'	,'desc_uso'=>'PUESTO SANITARIO'],
            ['codi_uso'=> '050208'	,'desc_uso'=>'CENTRO ESPECIALIZADO DE ASISTENCIA SOCIAL'],
            ['codi_uso'=> '050209'	,'desc_uso'=>'CEMENTERIO'],
            ['codi_uso'=> '050210'	,'desc_uso'=>'FUNERARIA'],
            ['codi_uso'=> '050303'	,'desc_uso'=>'TERMINAL TERRESTRE'],
            ['codi_uso'=> '050304'	,'desc_uso'=>'TERMINAL FERROVIARIO'],
            ['codi_uso'=> '050306'	,'desc_uso'=>'PLAYA'],
            ['codi_uso'=> '050307'	,'desc_uso'=>'SERVICIO RELACIONADO AL TRANSPORTE FERROVIARIO'],
            ['codi_uso'=> '050308'	,'desc_uso'=>'SERVICIO RELACIONADO AL TRANSPORTE TERRESTRE INTERPROVINCIAL'],
            ['codi_uso'=> '050309'	,'desc_uso'=>'SERVICIO RELACIONADO AL TRANSPORTE DE CARGA POR CARRETERA'],
            ['codi_uso'=> '050310'	,'desc_uso'=>'OTROS SERVICIOS DE TRANSPORTE TERRESTRE DE PASAJEROS EN LA CIUDAD'],
            ['codi_uso'=> '050312'	,'desc_uso'=>'SERVICIO RELACIONADO AL TRANSPORTE POR AGUA'],
            ['codi_uso'=> '050401'	,'desc_uso'=>'CORREO'],
            ['codi_uso'=> '050405'	,'desc_uso'=>'RADIO'],
            ['codi_uso'=> '050406'	,'desc_uso'=>'CABLES'],
            ['codi_uso'=> '050409'	,'desc_uso'=>'TELETIPO'],
            ['codi_uso'=> '050410'	,'desc_uso'=>'TELEFOTO'],
            ['codi_uso'=> '050411'	,'desc_uso'=>'PRENSA'],
            ['codi_uso'=> '050412'	,'desc_uso'=>'AGENCIA DE PRENSA'],
            ['codi_uso'=> '050413'	,'desc_uso'=>'AGENCIA NOTICIOSA'],
            ['codi_uso'=> '050415'	,'desc_uso'=>'INTERNET'],
            ['codi_uso'=> '050416'	,'desc_uso'=>'OTRO NO ESPECIFICADO'],
            ['codi_uso'=> '050503'	,'desc_uso'=>'SUMINISTRO DE VAPOR'],
            ['codi_uso'=> '050601'	,'desc_uso'=>'MERCADOS '],
            ['codi_uso'=> '050602'	,'desc_uso'=>'MERCADO AMBULATORIO'],
            ['codi_uso'=> '060201'	,'desc_uso'=>'PREFECTURA'],
            ['codi_uso'=> '060208'	,'desc_uso'=>'CUARTEL DE LA MARINA O BASE NAVAL'],
            ['codi_uso'=> '060301'	,'desc_uso'=>'FINANCIERA'],
            ['codi_uso'=> '060302'	,'desc_uso'=>'BOLSA DE VALORES'],
            ['codi_uso'=> '020309'	,'desc_uso'=>'DE BEBIDAS\, TABACO Y ARTICULOS CONEXOS'],
            ['codi_uso'=> '060305'	,'desc_uso'=>'OTRO ESTABLECIMIENTO FINANCIERO NO ESPECIFICADO'],
            ['codi_uso'=> '060307'	,'desc_uso'=>'BANCO COMERCIAL'],
            ['codi_uso'=> '060308'	,'desc_uso'=>'AGENCIA BANCARIA'],
            ['codi_uso'=> '060309'	,'desc_uso'=>'CAJA DE AHORRO'],
            ['codi_uso'=> '060310'	,'desc_uso'=>'MUTUAL'],
            ['codi_uso'=> '060314'	,'desc_uso'=>'SEGUROS'],
            ['codi_uso'=> '060315'	,'desc_uso'=>'OTRO SERVICIO DE SEGUROS NO ESPECIFICADO'],
            ['codi_uso'=> '060501'	,'desc_uso'=>'EMBAJADA'],
            ['codi_uso'=> '060502'	,'desc_uso'=>'CONSULADO'],
            ['codi_uso'=> '060504'	,'desc_uso'=>'ORGANISMO INTERNACIONAL'],
            ['codi_uso'=> '060601'	,'desc_uso'=>'CATEDRAL'],
            ['codi_uso'=> '060602'	,'desc_uso'=>'PARROQUIA'],
            ['codi_uso'=> '060603'	,'desc_uso'=>'CAPILLA'],
            ['codi_uso'=> '060604'	,'desc_uso'=>'TEMPLO DE LA IGLESIA ADVENTISTA'],
            ['codi_uso'=> '060605'	,'desc_uso'=>'TEMPLO DE LA IGLESIA ALIANZA CRISTIANA Y MISIONERA'],
            ['codi_uso'=> '060606'	,'desc_uso'=>'TEMPLO DE LA IGLESIA ANGLICANA'],
            ['codi_uso'=> '060607'	,'desc_uso'=>'TEMPLO DE LA IGLESIA BAUTISTA'],
            ['codi_uso'=> '060610'	,'desc_uso'=>'CONVENTO'],
            ['codi_uso'=> '060701'	,'desc_uso'=>'HOSPICIO'],
            ['codi_uso'=> '060702'	,'desc_uso'=>'ALBERGUE.'],
            ['codi_uso'=> '060703'	,'desc_uso'=>'PUERICULTORIO'],
            ['codi_uso'=> '060704'	,'desc_uso'=>'ASILO'],
            ['codi_uso'=> '060706'	,'desc_uso'=>'COMEDOR POPULAR'],
            ['codi_uso'=> '060707'	,'desc_uso'=>'LOCAL COMUNAL'],
            ['codi_uso'=> '060801'	,'desc_uso'=>'CULTURAL'],
            ['codi_uso'=> '060802'	,'desc_uso'=>'RELIGIOSA'],
            ['codi_uso'=> '060803'	,'desc_uso'=>'LABORAL'],
            ['codi_uso'=> '040308'	,'desc_uso'=>'CASA DE CITA Y PROSTÍBULO'],
            ['codi_uso'=> '050204'	,'desc_uso'=>'CLINICA ESPECIALIZADA'],
            ['codi_uso'=> '050205'	,'desc_uso'=>'CLINICA'],
            ['codi_uso'=> '050301'	,'desc_uso'=>'TERMINAL MARÍTIMO'],
            ['codi_uso'=> '050302'	,'desc_uso'=>'TERMINAL AEREO'],
            ['codi_uso'=> '050311'	,'desc_uso'=>'SERVICIO RELACIONADO AL TRANSPORTE AEREO'],
            ['codi_uso'=> '050402'	,'desc_uso'=>'TELÉFONO'],
            ['codi_uso'=> '050404'	,'desc_uso'=>'TELEGRAFO'],
            ['codi_uso'=> '050407'	,'desc_uso'=>'VIA SATELITE'],
            ['codi_uso'=> '050408'	,'desc_uso'=>'TELEX'],
            ['codi_uso'=> '050414'	,'desc_uso'=>'MENSAJERÍA'],
            ['codi_uso'=> '050501'	,'desc_uso'=>'LUZ Y FUERZA ELECTRICA'],
            ['codi_uso'=> '060205'	,'desc_uso'=>'CUARTEL DE LA GUARDIA REPUBLICANA POLICÍA NACIONAL'],
            ['codi_uso'=> '060206'	,'desc_uso'=>'CUARTEL DEL EJERCITO'],
            ['codi_uso'=> '060207'	,'desc_uso'=>'CUARTEL DE LA FUERZA AEREA'],
            ['codi_uso'=> '060303'	,'desc_uso'=>'AGENCIA CAMBIARÍA'],
            ['codi_uso'=> '060304'	,'desc_uso'=>'COMPAÑÍA DE PATENTES Y LICENCIAS'],
            ['codi_uso'=> '060306'	,'desc_uso'=>'BANCO DE LA ENTIDAD PUBLICA'],
            ['codi_uso'=> '060311'	,'desc_uso'=>'COOPERATIVA DE CREDITO'],
            ['codi_uso'=> '060312'	,'desc_uso'=>'CASA DE PRESTAMO'],
            ['codi_uso'=> '060316'	,'desc_uso'=>'CAJERO AUTOMÁTICO'],
            ['codi_uso'=> '060608'	,'desc_uso'=>'TEMPLO DE LA IGLESIA EVANGELICA'],
            ['codi_uso'=> '060609'	,'desc_uso'=>'TEMPLO DE LA IGLESIA DE JESUCRISTO DE LOS SANTOS DE LOS ULTIMOS DÍAS'],
            ['codi_uso'=> '060612'	,'desc_uso'=>'TEMPLO TESTIGO DE JEHOVA'],
            ['codi_uso'=> '060705'	,'desc_uso'=>'COMPAÑÍA DE BOMBEROS'],
            ['codi_uso'=> '060708'	,'desc_uso'=>'GUARDERÍA'],
            ['codi_uso'=> '060805'	,'desc_uso'=>'ASISTENCIA SOCIAL'],
            ['codi_uso'=> '060806'	,'desc_uso'=>'COMERCIAL'],
            ['codi_uso'=> '060807'	,'desc_uso'=>'PROFESIONAL'],
            ['codi_uso'=> '070101'	,'desc_uso'=>'SIN CONSTRUIR'],
            ['codi_uso'=> '090201'	,'desc_uso'=>'EDIFICIO '],
            ['codi_uso'=> '090202'	,'desc_uso'=>'QUINTA'],
            ['codi_uso'=> '090301'	,'desc_uso'=>'COMERCIO'],
            ['codi_uso'=> '010101'	,'desc_uso'=>'CASA HABITACION'],
            ['codi_uso'=> '020302'	,'desc_uso'=>'DE PRODUCTOS AGRÍCOLAS NO UTILIZADOS EN LA ALIMENTACION HUMANA'],
            ['codi_uso'=> '020324'	,'desc_uso'=>'DE VEHÍCULOS'],
            ['codi_uso'=> '020326'	,'desc_uso'=>'TIENDA MULTIPLE DE DIFERENTE RUBRO'],
            ['codi_uso'=> '020402'	,'desc_uso'=>'DE PROFESION MEDICA'],
            ['codi_uso'=> '020403'	,'desc_uso'=>'ESTUDIOS JURÍDICOS'],
            ['codi_uso'=> '020405'	,'desc_uso'=>'DE ENFERMERÍA'],
            ['codi_uso'=> '020407'	,'desc_uso'=>'DE CONSTRUCCION.'],
            ['codi_uso'=> '020408'	,'desc_uso'=>'DE BIENES Y EXPORTACION / IMPORTACION.'],
            ['codi_uso'=> '020501'	,'desc_uso'=>'DE ALIMENTACION Y BEBIDAS / RESTAURANTE'],
            ['codi_uso'=> '020502'	,'desc_uso'=>'DE VESTIMENTA / SASTRERÍA'],
            ['codi_uso'=> '020504'	,'desc_uso'=>'DE HIGIENE Y ESTETICA PERSONAL / PELUQUERÍA'],
            ['codi_uso'=> '020506'	,'desc_uso'=>'TECNICOS ESPECIALIZADOS.'],
            ['codi_uso'=> '020507'	,'desc_uso'=>'DE MECÁNICA AUTOMOTRIZ.'],
            ['codi_uso'=> '020508'	,'desc_uso'=>'DE MECÁNICA EN GENERAL Y ELECTRICIDAD.'],
            ['codi_uso'=> '020509'	,'desc_uso'=>'PARA APARATOS Y MUEBLES PREFERENTEMENTE DE USO DOMESTICO.'],
            ['codi_uso'=> '020510'	,'desc_uso'=>'DE MECÁNICA FINA.'],
            ['codi_uso'=> '030102'	,'desc_uso'=>'EXPLOTACION DE MINAS'],
            ['codi_uso'=> '030204'	,'desc_uso'=>'FABRICACION DEL PAPEL Y PRODUCTOS DEL PAPEL'],
            ['codi_uso'=> '030205'	,'desc_uso'=>'FABRICACION DE SUSTANCIAS Y PRODUCTOS QUÍMICOS DERIVADOS DEL PETROLEO'],
            ['codi_uso'=> '030206'	,'desc_uso'=>'FABRICACION DE PRODUCTOS MINERALES NO METALICOS EXCEPTO LOS DERIVADOS DEL PETROLEO Y CARBON.'],
            ['codi_uso'=> '030207'	,'desc_uso'=>'INDUSTRIAS METÁLICAS BÁSICAS.'],
            ['codi_uso'=> '030208'	,'desc_uso'=>'FABRICACION DE PRODUCTOS METALICOS'],
            ['codi_uso'=> '040105'	,'desc_uso'=>'HIPODROMO'],
            ['codi_uso'=> '040107'	,'desc_uso'=>'CLUB O CÍRCULO.'],
            ['codi_uso'=> '040114'	,'desc_uso'=>'GALERÍA DE TIRO.'],
            ['codi_uso'=> '040115'	,'desc_uso'=>'PISCINA DE NATACION.'],
            ['codi_uso'=> '040203'	,'desc_uso'=>'SALA DE EXPOSICION'],
            ['codi_uso'=> '040204'	,'desc_uso'=>'MONUMENTO ARQUEOLOGICO PREHISPANICO/HISTORICO COLONIAL- REPUBLICANO.'],
            ['codi_uso'=> '040206'	,'desc_uso'=>'JARDÍN BOTÁNICO.'],
            ['codi_uso'=> '040207'	,'desc_uso'=>'ZOOLOGICO.'],
            ['codi_uso'=> '040304'	,'desc_uso'=>'PEÑA.'],
            ['codi_uso'=> '040305'	,'desc_uso'=>'CAFE TEATRO'],
            ['codi_uso'=> '040306'	,'desc_uso'=>'SALON DE BAILE.'],
            ['codi_uso'=> '050101'	,'desc_uso'=>'EDUCACION INICIAL ESTATAL'],
            ['codi_uso'=> '050102'	,'desc_uso'=>'EDUCACION INICIAL PARTICULAR'],
            ['codi_uso'=> '050103'	,'desc_uso'=>'EDUCACION PRIMARIA ESTATAL'],
            ['codi_uso'=> '050104'	,'desc_uso'=>'EDUCACION PRIMARIA PARTICULAR'],
            ['codi_uso'=> '050105'	,'desc_uso'=>'EDUCACION SECUNDARIA ESTATAL'],
            ['codi_uso'=> '050106'	,'desc_uso'=>'EDUCACION SECUNDARIA PARTICULAR'],
            ['codi_uso'=> '050107'	,'desc_uso'=>'EDUCACION PRIMARIA-SECUNDARIA ESTATAL'],
            ['codi_uso'=> '050108'	,'desc_uso'=>'EDUCACION PRIMARIA-SECUNDARIA PARTICULAR'],
            ['codi_uso'=> '050109'	,'desc_uso'=>'EDUCACION PRE-UNIVERSITARIA / ACADEMIA'],
            ['codi_uso'=> '050110'	,'desc_uso'=>'EDUCACION SUPERIOR UNIVERSITARIA ESTATAL'],
            ['codi_uso'=> '050111'	,'desc_uso'=>'EDUCACION SUPERIOR UNIVERSITARIA PARTICULAR'],
            ['codi_uso'=> '050112'	,'desc_uso'=>'EDUCACION SUPERIOR INSTITUTO ESTATAL.'],
            ['codi_uso'=> '050113'	,'desc_uso'=>'EDUCACION SUPERIOR INSTITUTO PARTICULAR'],
            ['codi_uso'=> '050114'	,'desc_uso'=>'CALIFICACION PROFESIONAL ESPECIALIZADA'],
            ['codi_uso'=> '050115'	,'desc_uso'=>'EDUCACION ESPECIAL'],
            ['codi_uso'=> '050305'	,'desc_uso'=>'DEPOSITO Y ALMACENAMIENTO'],
            ['codi_uso'=> '050403'	,'desc_uso'=>'TELEVISION'],
            ['codi_uso'=> '050502'	,'desc_uso'=>'PRODUCCION Y DISTRIBUCION DE GAS'],
            ['codi_uso'=> '050504'	,'desc_uso'=>'CENTRO DE CAPTACION'],
            ['codi_uso'=> '050505'	,'desc_uso'=>'CENTRAL DE GENERACION ELECTRICA'],
            ['codi_uso'=> '050506'	,'desc_uso'=>'SUB ESTACION DE TELECOMUNICACIONES'],
            ['codi_uso'=> '060101'	,'desc_uso'=>'EDIFICACION UTILIZADA POR EL GOBIERNO CENTRAL'],
            ['codi_uso'=> '060102'	,'desc_uso'=>'EDIFICACION UTILIZADA POR EL GOBIERNO REGIONAL'],
            ['codi_uso'=> '060103'	,'desc_uso'=>'EDIFICACION UTILIZADA POR EL GOBIERNO LOCAL'],
            ['codi_uso'=> '060104'	,'desc_uso'=>'EDIFICACION UTILIZADA POR EL GOBIERNO NO ESPECIFICADO'],
            ['codi_uso'=> '060202'	,'desc_uso'=>'ESTACION DE LA POLICÍA NACIONAL'],
            ['codi_uso'=> '060203'	,'desc_uso'=>'CENTRO DE INSTRUCCION DE LAS FUERZAS ARMADAS'],
            ['codi_uso'=> '060204'	,'desc_uso'=>'CENTRO DE INSTRUCCION DE LAS FUERZAS POLICIALES.'],
            ['codi_uso'=> '060209'	,'desc_uso'=>'CENTRO DE REHABILITACION Y ASISTENCIA SOCIAL / C.R.A.S.- CÁRCELES.'],
            ['codi_uso'=> '060313'	,'desc_uso'=>'OTRA INSTITUCION MONETARIA NO ESPECIFICADA'],
            ['codi_uso'=> '060317'	,'desc_uso'=>'ADMINISTRACION FONDO DE PENSIONES / AFP'],
            ['codi_uso'=> '060401'	,'desc_uso'=>'INSTITUTO DE INVESTIGACION Y CIENTÍFICO'],
            ['codi_uso'=> '060503'	,'desc_uso'=>'LEGACION'],
            ['codi_uso'=> '060611'	,'desc_uso'=>'SALA DE REUNION DEPENDIENTE DE LA ENTIDAD RELIGIOSA'],
            ['codi_uso'=> '060804'	,'desc_uso'=>'POLÍTICA'],
            ['codi_uso'=> '070201'	,'desc_uso'=>'EN CONSTRUCCION'],
            ['codi_uso'=> '070301'	,'desc_uso'=>'CONSTRUCCION PARCIAL'],
            ['codi_uso'=> '070401'	,'desc_uso'=>'CON CONSTRUCCION DE TERCEROS'],
            ['codi_uso'=> '070402'	,'desc_uso'=>'TERRENO CONSTRUCCION PARCIAL'],
            ['codi_uso'=> '080101'	,'desc_uso'=>'CON CONSTRUCCION'],
            ['codi_uso'=> '090101'	,'desc_uso'=>'CASA HABITACION'],
            ['codi_uso'=> '110101'	,'desc_uso'=>'CASA HABITACION CON ACTIVIDAD ECONOMICA'],
              
        ];
        foreach ($usos as $uso) {
            Uso::create($uso);
        } 
    }
}
